# Generated by Django 5.0.6 on 2024-09-17 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('POSMagicApp', '0010_alter_product_category'),
        ('production', '0081_alter_lpo_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.PositiveIntegerField(choices=[(5, '5%'), (10, '10%'), (15, '15%')], default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to='POSMagicApp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='BranchInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='salon.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('attended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='POSMagicApp.staff')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='salon.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='POSMagicApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SalonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.PositiveIntegerField(choices=[(5, '5%'), (10, '10%'), (15, '15%')], default=5)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_products', to='production.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('branch_inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.branchinventory')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='salon.sale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.salonproduct')),
            ],
        ),
        migrations.AddField(
            model_name='branchinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_inventory', to='salon.salonproduct'),
        ),
        migrations.CreateModel(
            name='SaleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon.sale')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSMagicApp.staff')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service')),
            ],
        ),
    ]
