# Generated by Django 5.0.6 on 2024-09-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0010_alter_product_category'),
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='SalonBranch',
        ),
    ]
