# Generated by Django 5.0.6 on 2024-09-18 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_inventoryupdatehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryupdatehistory',
            old_name='updated_quantity',
            new_name='quantity_change',
        ),
        migrations.RemoveField(
            model_name='inventoryupdatehistory',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventoryupdatehistory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_histories', to='salon.salonbranch'),
        ),
        migrations.AddField(
            model_name='inventoryupdatehistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_histories', to='salon.salonproduct'),
        ),
        migrations.AlterField(
            model_name='inventoryupdatehistory',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventoryupdatehistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
