# Generated by Django 5.0.6 on 2024-09-19 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0081_alter_lpo_amount_paid'),
        ('salon', '0005_rename_updated_quantity_inventoryupdatehistory_quantity_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalrequisition',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_requisitions', to='production.supplier'),
        ),
        migrations.AlterField(
            model_name='generalrequisitionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_requisition_items', to='salon.salonproduct'),
        ),
    ]
