# Generated by Django 5.0.6 on 2024-10-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_alter_salonrestockrequestitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonrestockrequestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.salonproduct'),
        ),
    ]
