# Generated by Django 5.0.6 on 2024-10-03 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0092_alter_requisition_price_list_document'),
        ('salon', '0011_alter_salonrestockrequestitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonrestockrequestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.livaramainstore'),
        ),
    ]
