# Generated by Django 5.0.6 on 2024-10-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_alter_salonrestockrequestitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonrestockrequestitem',
            old_name='product',
            new_name='livara_main_store',
        ),
    ]
