# Generated by Django 5.0.6 on 2024-10-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0013_rename_product_salonrestockrequestitem_livara_main_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonrestockrequestitem',
            old_name='livara_main_store',
            new_name='product',
        ),
    ]
