# Generated by Django 5.0.6 on 2024-10-03 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0092_alter_requisition_price_list_document'),
        ('salon', '0015_alter_salonrestockrequestitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonproduct',
            name='livara_main_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.livaramainstore'),
        ),
    ]
