# Generated by Django 5.0.6 on 2024-10-08 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0093_paymentvoucher_pay_by_paymentvoucher_voucher_notes'),
        ('salon', '0017_alter_salonrestockrequestitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonrestockrequestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salonrestockrequestitems', to='production.livaramainstore'),
        ),
    ]
