# Generated by Django 3.2.5 on 2024-04-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
