# Generated by Django 3.2.5 on 2024-04-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0009_customer_profile_image'),
        ('payment', '0003_auto_20240429_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='POSMagicApp.staff'),
        ),
    ]
