# Generated by Django 3.2.5 on 2024-05-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_details_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True),
        ),
    ]
