# Generated by Django 3.2.5 on 2024-05-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_transaction_commission_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
