# Generated by Django 3.2.5 on 2024-05-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_transaction_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
