# Generated by Django 3.2.5 on 2024-05-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_transaction_commission_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=5, null=True),
        ),
    ]
