# Generated by Django 3.2.5 on 2024-05-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20240524_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonmaterialinventory',
            name='material',
        ),
        migrations.DeleteModel(
            name='SalonMaterial',
        ),
        migrations.DeleteModel(
            name='SalonMaterialInventory',
        ),
    ]
