# Generated by Django 3.2.5 on 2024-06-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0010_alter_product_category'),
        ('payment', '0016_staffcommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_number', models.CharField(max_length=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSMagicApp.customer')),
                ('transactions', models.ManyToManyField(to='payment.Transaction')),
            ],
        ),
    ]
