# Generated by Django 3.2.5 on 2024-04-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_rawmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment', models.IntegerField(default=0)),
                ('raw_material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled')], default='pending', max_length=255)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.supplier')),
            ],
        ),
    ]
