# Generated by Django 3.2.5 on 2024-04-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_purchaseorder_rawmaterialinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialinventory',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='production.rawmaterial'),
        ),
    ]
