# Generated by Django 3.2.5 on 2024-04-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_purchaseorder_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='fullfilled_qty',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
