# Generated by Django 3.2.5 on 2024-05-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_productionbatch_productioningredient_productionrecipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductionRecipe',
            new_name='Production',
        ),
        migrations.RenameField(
            model_name='productioningredient',
            old_name='recipe',
            new_name='product',
        ),
    ]
