# Generated by Django 3.2.5 on 2024-05-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_auto_20240506_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionbatch',
            old_name='recipe',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productioningredient',
            old_name='quantity_per_unit_recipe_volume',
            new_name='quantity_per_unit_product_volume',
        ),
    ]
