# Generated by Django 3.2.5 on 2024-05-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_auto_20240506_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='total_volume',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
