# Generated by Django 3.2.5 on 2024-05-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_alter_production_total_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioningredient',
            name='quantity_per_unit_product_volume',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
