# Generated by Django 3.2.5 on 2024-05-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_alter_productioningredient_quantity_per_unit_product_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioningredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productioningredients', to='production.production'),
        ),
    ]
