# Generated by Django 3.2.5 on 2024-05-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_manufacturedproductinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturedproductinventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
