# Generated by Django 3.2.5 on 2024-05-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_manufacturedproductinventory_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='unit_measurement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
