# Generated by Django 3.2.5 on 2024-05-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_rawmaterial_unit_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactureproduct',
            name='labor_cost_per_unit',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
