# Generated by Django 3.2.5 on 2024-05-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_auto_20240517_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactureproduct',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
