# Generated by Django 3.2.5 on 2024-06-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_alter_restockrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturedproductinventory',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manufacturedproductinventory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
