# Generated by Django 3.2.5 on 2024-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_productionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='approved_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
