# Generated by Django 3.2.5 on 2024-06-14 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0027_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_restocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restockrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_restocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
