# Generated by Django 5.0.6 on 2024-06-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0030_alter_saleitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesale',
            name='due_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
