# Generated by Django 5.0.6 on 2024-06-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0033_saleitem_total_price_alter_storesale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesale',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('delivered', 'Delivered'), ('paid', 'Paid')], default='ordered', max_length=255),
        ),
    ]
