# Generated by Django 5.0.6 on 2024-07-15 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0036_alter_storesale_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactureproduct',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufactured_products', to='production.productionorder'),
        ),
    ]
