# Generated by Django 5.0.6 on 2024-07-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0039_livaramainstore_storetransfer_storetransferitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransfer',
            name='notes',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
