# Generated by Django 5.0.6 on 2024-07-17 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0043_alter_saleitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.livaramainstore')),
                ('restock_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.restockrequest')),
            ],
        ),
    ]
