# Generated by Django 5.0.6 on 2024-07-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0044_restockrequestitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restockrequest',
            name='quantity',
        ),
    ]
