# Generated by Django 5.0.6 on 2024-07-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0046_remove_restockrequest_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restockrequest',
            name='product',
        ),
    ]
