# Generated by Django 5.0.6 on 2024-08-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0051_alter_productioningredient_quantity_per_unit_product_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
