# Generated by Django 5.0.6 on 2024-08-23 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0052_alter_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_no', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('checking', 'Checking'), ('delivered', 'Delivered')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='LPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('invoice_document', models.FileField(upload_to='uploads/products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_duration', models.IntegerField(choices=[(0, '0 days'), (10, '10 days'), (20, '20 days'), (30, '30 days')], default=10)),
                ('payment_option', models.CharField(choices=[('bank', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash')], default='bank', max_length=20)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.requisition')),
            ],
        ),
        migrations.AddField(
            model_name='requisition',
            name='items',
            field=models.ManyToManyField(through='production.RequisitionItem', to='production.rawmaterial'),
        ),
    ]
