# Generated by Django 5.0.6 on 2024-08-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0053_alter_purchaseorder_order_number_requisition_lpo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lpo',
            name='payment_option',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash')], default='cash', max_length=20),
        ),
    ]
