# Generated by Django 5.0.6 on 2024-08-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0054_requisitionitem_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='delivered_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
