# Generated by Django 5.0.6 on 2024-08-28 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0056_goodsreceivednote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscrepancyDeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(choices=[('refund', 'Refund from Supplier'), ('replace', 'Replace Missing Items')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('goods_received_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.goodsreceivednote')),
            ],
        ),
    ]
