# Generated by Django 5.0.6 on 2024-08-28 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0057_discrepancydeliveryreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_items', to='production.requisition'),
        ),
    ]
