# Generated by Django 5.0.6 on 2024-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0059_alter_requisitionitem_requisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioningredient',
            name='quantity_per_unit_product_volume',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
