# Generated by Django 5.0.6 on 2024-08-29 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0060_alter_productioningredient_quantity_per_unit_product_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.unitofmeasurement'),
        ),
    ]
