# Generated by Django 5.0.6 on 2024-08-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0061_production_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
