# Generated by Django 5.0.6 on 2024-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0062_requisition_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpo',
            name='lpo_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
