# Generated by Django 5.0.6 on 2024-08-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0063_lpo_lpo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='reason',
            field=models.CharField(blank=True, choices=[('expired', 'Expired'), ('quality', 'Poor Quality'), ('spillage', 'Spillage')], max_length=255, null=True),
        ),
    ]
