# Generated by Django 5.0.6 on 2024-08-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0064_alter_goodsreceivednote_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='gcr_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
