# Generated by Django 5.0.6 on 2024-09-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0066_alter_productioningredient_quantity_per_unit_product_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioningredient',
            name='quantity_per_unit_product_volume',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
