# Generated by Django 5.0.6 on 2024-09-02 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0067_alter_productioningredient_quantity_per_unit_product_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_note_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('total_deducted_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('discrepancy_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='production.discrepancydeliveryreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReplaceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replace_note_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=10)),
                ('discrepancy_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replace_notes', to='production.discrepancydeliveryreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReplaceNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivered_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_to_replace', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
                ('replace_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.replacenote')),
            ],
        ),
    ]
