# Generated by Django 5.0.6 on 2024-09-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0068_debitnote_replacenote_replacenoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='reason',
            field=models.CharField(blank=True, choices=[('Successful', 'Successful'), ('expired', 'Expired'), ('quality', 'Poor Quality'), ('spillage', 'Spillage')], max_length=255, null=True),
        ),
    ]
