# Generated by Django 5.0.6 on 2024-09-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0069_alter_goodsreceivednote_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacenote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
    ]
