# Generated by Django 5.0.6 on 2024-09-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0071_alter_rawmaterialinventory_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
