# Generated by Django 5.0.6 on 2024-09-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0072_alter_rawmaterial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturedproductinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
