# Generated by Django 5.0.6 on 2024-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0073_alter_manufacturedproductinventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='prod_order_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
