# Generated by Django 5.0.6 on 2024-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0074_productionorder_prod_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactureproduct',
            name='batch_number',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
