# Generated by Django 5.0.6 on 2024-09-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0075_alter_manufactureproduct_batch_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufactureproduct',
            name='labor_cost_per_unit',
        ),
    ]
