# Generated by Django 5.0.6 on 2024-09-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0076_remove_manufactureproduct_labor_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialinventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
