# Generated by Django 5.0.6 on 2024-09-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0077_rawmaterialinventory_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpo',
            name='quotation_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/products/'),
        ),
    ]
