# Generated by Django 5.0.6 on 2024-09-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0078_lpo_quotation_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpo',
            name='payment_duration',
            field=models.IntegerField(choices=[(0, 'Immediate Payment'), (10, '10 days'), (20, '20 days'), (30, '30 days'), (45, '45 days')], default=10),
        ),
    ]
