# Generated by Django 5.0.6 on 2024-09-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0079_alter_lpo_payment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpo',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lpo',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='lpo',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
