# Generated by Django 5.0.6 on 2024-09-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0080_lpo_amount_paid_lpo_is_paid_lpo_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpo',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=10, null=True),
        ),
    ]
