# Generated by Django 5.0.6 on 2024-09-19 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0081_alter_lpo_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('full', 'Full Payment'), ('partial', 'Partial Payment')], default='partial', max_length=20)),
                ('lpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.lpo')),
            ],
        ),
    ]
