# Generated by Django 5.0.6 on 2024-09-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0083_paymentvoucher_voucher_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='price_list_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/products/'),
        ),
    ]
