# Generated by Django 5.0.6 on 2024-09-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0085_alter_requisition_price_list_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='price_list_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/products/'),
        ),
    ]
