# Generated by Django 5.0.6 on 2024-09-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0087_alter_requisition_price_list_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpo',
            name='is_paid',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
