# Generated by Django 5.0.6 on 2024-10-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0090_storetransfer_delivery_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransferitem',
            name='delivered_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
