# Generated by Django 5.0.6 on 2024-10-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0091_storetransferitem_delivered_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='price_list_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/products/'),
        ),
    ]
