# Generated by Django 5.0.6 on 2024-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0092_alter_requisition_price_list_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='pay_by',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='voucher_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
