# Generated by Django 5.0.6 on 2024-10-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0094_inventoryadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinventory',
            name='previous_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
