# Generated by Django 5.0.6 on 2024-10-22 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0098_storeinventory_low_stock_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StoreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_services', to='production.servicename')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_services', to='production.store')),
            ],
            options={
                'unique_together': {('store', 'service')},
            },
        ),
    ]
