# Generated by Django 5.0.6 on 2024-10-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0102_accessoryinventoryadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
