# Generated by Django 5.0.6 on 2024-10-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0103_accessory_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstoreaccessoryrequisitionitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
