# Generated by Django 5.0.6 on 2024-10-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0012_remove_staff_branch'),
        ('production', '0107_accessoryinventoryadjustment_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_sales', to='POSMagicApp.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.servicename')),
                ('staff', models.ManyToManyField(related_name='services_handled', to='POSMagicApp.staff')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_sales', to='production.store')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSaleAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.storeaccessoryinventory')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_items', to='production.servicesale')),
            ],
        ),
        migrations.AddField(
            model_name='servicesale',
            name='accessories_used',
            field=models.ManyToManyField(blank=True, to='production.servicesaleaccessory'),
        ),
        migrations.CreateModel(
            name='ServiceSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.storeinventory')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='production.servicesale')),
            ],
        ),
        migrations.AddField(
            model_name='servicesale',
            name='products_sold',
            field=models.ManyToManyField(blank=True, to='production.servicesaleproduct'),
        ),
    ]
