# Generated by Django 5.0.6 on 2024-10-23 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0108_servicesale_servicesaleaccessory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesale',
            name='paid_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('paid', 'Paid')], default='not_paid', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceSaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobilemoney', 'Mobile Money'), ('both', 'Both')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='production.servicesale')),
            ],
        ),
    ]
