# Generated by Django 5.0.6 on 2024-10-25 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0109_servicesale_paid_status_servicesaleinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStoreAccessoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('opening_stock', models.PositiveIntegerField(default=0)),
                ('closing_stock', models.PositiveIntegerField(default=0)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.accessory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_accessory_stocks', to='production.store')),
            ],
            options={
                'unique_together': {('store', 'accessory', 'date')},
            },
        ),
    ]
