# Generated by Django 5.0.6 on 2024-10-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0110_dailystoreaccessorystock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoryinventoryadjustment',
            name='store',
        ),
        migrations.AlterField(
            model_name='dailystoreaccessorystock',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stocks', to='production.accessory'),
        ),
    ]
