# Generated by Django 5.0.6 on 2024-10-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0111_remove_accessoryinventoryadjustment_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryinventoryadjustment',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='production.store'),
        ),
    ]
