# Generated by Django 5.0.6 on 2024-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0112_accessoryinventoryadjustment_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
