# Generated by Django 5.0.6 on 2024-10-28 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0114_manufacturedproductingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessoryinventoryadjustment',
            old_name='adjustment_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='accessoryinventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='accessoryinventoryadjustment',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='accessoryinventoryadjustment',
            name='quantity_adjusted',
        ),
        migrations.RemoveField(
            model_name='accessoryinventoryadjustment',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='accessoryinventoryadjustment',
            name='store',
        ),
        migrations.AddField(
            model_name='accessoryinventoryadjustment',
            name='accessory_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.accessoryinventory'),
        ),
        migrations.AddField(
            model_name='accessoryinventoryadjustment',
            name='adjustment',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accessoryinventoryadjustment',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='DailyStoreAccessoryStock',
        ),
    ]
