# Generated by Django 5.0.6 on 2024-10-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0115_rename_adjustment_date_accessoryinventoryadjustment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryinventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
