# Generated by Django 5.0.6 on 2024-10-30 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0117_storetransferitem_approved_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storetransferitem',
            name='approved_quantity',
        ),
        migrations.AddField(
            model_name='restockrequestitem',
            name='approved_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restockrequestitem',
            name='delivered_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferapproval',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.restockrequest'),
        ),
    ]
