# Generated by Django 5.0.6 on 2024-10-31 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0119_restockrequest_liv_store_transfer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livaramainstore',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livara_main_store', to='production.manufacturedproductinventory'),
        ),
    ]
