# Generated by Django 5.0.6 on 2024-10-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0120_alter_livaramainstore_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
