# Generated by Django 5.0.6 on 2024-10-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0121_production_wholesale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='chosen_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
