# Generated by Django 5.0.6 on 2024-11-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0012_remove_staff_branch'),
        ('production', '0122_remove_saleitem_unit_price_saleitem_chosen_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesale',
            name='accessories_used',
        ),
        migrations.RemoveField(
            model_name='servicesaleproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='servicesaleproduct',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='servicesale',
            name='products_sold',
        ),
        migrations.RemoveField(
            model_name='servicesale',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicesale',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='servicesale',
            name='total_price',
        ),
        migrations.AddField(
            model_name='servicesale',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicesale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicesale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AccessorySaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.storeaccessoryinventory')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.servicesale')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.servicesale')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.storeservice')),
                ('staff', models.ManyToManyField(related_name='service_sales', to='POSMagicApp.staff')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceSaleAccessory',
        ),
        migrations.DeleteModel(
            name='ServiceSaleProduct',
        ),
    ]
