# Generated by Django 5.0.6 on 2024-11-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0123_remove_servicesale_accessories_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.storeinventory')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.servicesale')),
            ],
        ),
    ]
