# Generated by Django 5.0.6 on 2024-11-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0126_alter_storeaccessoryinventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='carrefour_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
