# Generated by Django 5.0.6 on 2024-11-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0127_production_carrefour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsaleitem',
            name='price_type',
            field=models.CharField(choices=[('wholesale', 'Wholesale Price'), ('carrefour', 'Carrefour Price'), ('retail', 'Retail Price')], default='retail', max_length=10),
        ),
    ]
