# Generated by Django 5.0.6 on 2024-11-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0128_productsaleitem_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit_measurement',
            field=models.CharField(blank=True, default='units', max_length=10),
        ),
    ]
