# Generated by Django 5.0.6 on 2024-11-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0129_alter_rawmaterial_unit_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialinventory',
            name='adjustment',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8),
        ),
    ]
