# Generated by Django 5.0.6 on 2024-11-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0131_incidentwriteoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
