# Generated by Django 5.0.6 on 2024-11-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0132_alter_rawmaterial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rawmaterialinventory',
            name='adjustment',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
