# Generated by Django 5.0.6 on 2024-11-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0133_alter_rawmaterial_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='rawmaterialinventory',
            name='adjustment',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
