# Generated by Django 5.0.6 on 2024-11-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0134_alter_rawmaterial_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
