# Generated by Django 5.0.6 on 2024-11-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0135_alter_requisitionitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
