# Generated by Django 5.0.6 on 2024-12-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0136_alter_requisitionitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='supplier',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='supplier',
            field=models.ManyToManyField(related_name='raw_materials', to='production.supplier'),
        ),
    ]
