# Generated by Django 5.0.6 on 2024-12-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0138_remove_rawmaterial_supplier_rawmaterial_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='suppliers',
            field=models.ManyToManyField(related_name='supplied_raw_materials', to='production.supplier'),
        ),
    ]
