# Generated by Django 5.0.6 on 2024-12-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0139_rawmaterial_suppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='supplier',
        ),
    ]
