# Generated by Django 5.0.6 on 2024-12-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0141_storeinventoryadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalaccessoryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
