# Generated by Django 5.0.6 on 2024-12-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0142_alter_internalaccessoryrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeinventoryadjustment',
            old_name='adjustment_type',
            new_name='adjustment',
        ),
    ]
