# Generated by Django 5.0.6 on 2024-12-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0144_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesale',
            name='service_sale_number',
            field=models.CharField(default='none', max_length=20, unique=True),
        ),
    ]
