# Generated by Django 5.0.6 on 2024-12-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0145_servicesale_service_sale_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesale',
            name='service_sale_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
