# Generated by Django 5.0.6 on 2025-01-06 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0147_alter_servicesale_service_sale_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSaleReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=10, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withholding_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.storesale')),
            ],
        ),
    ]
