# Generated by Django 5.0.6 on 2025-01-25 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0150_pricegroup_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='price_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.pricegroup'),
        ),
    ]
