# Generated by Django 5.0.6 on 2025-01-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0151_saleitem_price_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturedproductinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
