# Generated by Django 5.0.6 on 2025-01-31 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0012_remove_staff_branch'),
        ('production', '0152_alter_manufacturedproductinventory_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStaffCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_commissions', to='POSMagicApp.staff')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('staff', 'month')},
            },
        ),
        migrations.CreateModel(
            name='StaffCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('monthly_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.monthlystaffcommission')),
                ('service_sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_commissions', to='production.servicesaleitem')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='POSMagicApp.staff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
