# Generated by Django 5.0.6 on 2025-02-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0154_productionorder_rejected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='delivered_quantity',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
