# Generated by Django 5.0.6 on 2025-02-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0155_alter_requisitionitem_delivered_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='delivered_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
