# Generated by Django 5.0.6 on 2025-02-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0156_alter_requisitionitem_delivered_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricegroup',
            name='description',
            field=models.CharField(default='No Description', max_length=255, unique=True),
        ),
    ]
