# Generated by Django 5.0.6 on 2025-03-06 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0157_pricegroup_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('batch_number', models.CharField(max_length=50)),
                ('reason', models.CharField(choices=[('expired', 'Expired Product'), ('damaged', 'Damaged/Broken'), ('spillage', 'Spillage'), ('quality', 'Quality Issues'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_writeoffs', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('main_store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='production.livaramainstore')),
            ],
        ),
    ]
