# Generated by Django 5.0.6 on 2025-03-12 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0158_storewriteoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsaleitem',
            name='price_type',
        ),
        migrations.AddField(
            model_name='productsaleitem',
            name='price_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.pricegroup'),
        ),
    ]
