# Generated by Django 5.0.6 on 2025-03-25 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0012_remove_staff_branch'),
        ('production', '0159_remove_productsaleitem_price_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsaleitem',
            name='staff',
            field=models.ManyToManyField(help_text='Staff member who recommended this product', related_name='product_sales', to='POSMagicApp.staff'),
        ),
        migrations.CreateModel(
            name='StaffProductCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_sale_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='production.productsaleitem')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_commissions', to='POSMagicApp.staff')),
            ],
        ),
    ]
