# Generated by Django 5.0.6 on 2025-03-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0160_productsaleitem_staff_staffproductcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffproductcommission',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
