# Generated by Django 5.0.6 on 2025-03-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0012_remove_staff_branch'),
        ('production', '0161_staffproductcommission_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsaleitem',
            name='staff',
        ),
        migrations.AddField(
            model_name='productsaleitem',
            name='staff',
            field=models.ForeignKey(help_text='Staff member who recommended this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sales', to='POSMagicApp.staff'),
        ),
    ]
