# Generated by Django 5.0.6 on 2025-07-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0162_remove_productsaleitem_staff_productsaleitem_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum credit allowed', max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('net_7', 'Net 7 Days'), ('net_15', 'Net 15 Days'), ('net_30', 'Net 30 Days'), ('net_45', 'Net 45 Days'), ('net_60', 'Net 60 Days'), ('advance_payment', 'Advance Payment')], default='net_30', max_length=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='quality_rating',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='reliability_score',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Score out of 10', max_digits=3),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='delivered_quantity',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='RawMaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.supplier')),
            ],
        ),
    ]
