# Generated by Django 5.0.6 on 2025-07-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0164_alter_rawmaterialprice_effective_date_pricealert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitionitem',
            options={'ordering': ['raw_material__name']},
        ),
    ]
