# Generated by Django 5.0.6 on 2025-07-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0165_alter_requisitionitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentwriteoff',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
