# Generated by Django 5.0.6 on 2025-07-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0166_alter_incidentwriteoff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='reorder_point',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
