# Generated by Django 5.0.6 on 2025-08-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0167_alter_rawmaterial_reorder_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='airtime_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Communication costs (airtime, internet)', max_digits=10),
        ),
        migrations.AddField(
            model_name='requisition',
            name='expense_notes',
            field=models.TextField(blank=True, help_text='Notes about additional expenses', null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='handling_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Handling and processing fees', max_digits=10),
        ),
        migrations.AddField(
            model_name='requisition',
            name='other_expenses',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other miscellaneous expenses', max_digits=10),
        ),
        migrations.AddField(
            model_name='requisition',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Transport/Delivery costs', max_digits=10),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='manual_price_reason',
            field=models.CharField(blank=True, help_text='Reason for manual price entry', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='price_updated_on_delivery',
            field=models.BooleanField(default=False, help_text='Whether supplier price was updated upon delivery'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='pricing_source',
            field=models.CharField(choices=[('system', 'System Price'), ('manual', 'Manual Price Entry')], default='system', help_text='Source of the price', max_length=10),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='system_price_at_creation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='System price when item was created', max_digits=10, null=True),
        ),
    ]
