# Generated by Django 5.0.6 on 2025-08-06 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_manufacturingrecord_paymentrecord_storebudget_and_more'),
        ('production', '0168_add_manual_pricing_and_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='airtime_cost',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='expense_notes',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='handling_cost',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='other_expenses',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='transport_cost',
        ),
        migrations.CreateModel(
            name='RequisitionExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=10)),
                ('description', models.CharField(help_text='Description of this expense', max_length=255)),
                ('expense_account', models.ForeignKey(help_text='Select expense account from chart of accounts', limit_choices_to={'account_type': 'expense', 'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccounts')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='production.requisition')),
            ],
            options={
                'ordering': ['expense_account__account_code'],
            },
        ),
    ]
