# Generated by Django 5.0.6 on 2025-08-07 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0169_remove_requisition_airtime_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Tax code (e.g., VAT18, VAT0)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Tax name (e.g., VAT 18%, Zero Rated)', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate percentage (e.g., 18.00 for 18%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tax code is active')),
                ('description', models.TextField(blank=True, help_text='Additional description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='requisition',
            name='amounts_are_tax_inclusive',
            field=models.BooleanField(default=False, help_text='If checked, amounts include tax'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='project',
            field=models.CharField(blank=True, help_text='Project code or name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='default_tax_code',
            field=models.ForeignKey(blank=True, help_text='Default tax code for items in this requisition', null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.taxcode'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='tax_code',
            field=models.ForeignKey(blank=True, help_text='Tax code for this item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.taxcode'),
        ),
    ]
