# Generated by Django 5.0.6 on 2025-08-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_manufacturingrecord_paymentrecord_storebudget_and_more'),
        ('production', '0170_taxcode_requisition_amounts_are_tax_inclusive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitionexpenseitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='requisitionitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='requisitionitem',
            name='price_updated_on_delivery',
        ),
        migrations.RemoveField(
            model_name='requisitionitem',
            name='project',
        ),
        migrations.AddField(
            model_name='requisitionexpenseitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitionexpenseitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='lpo',
            name='payment_duration',
            field=models.IntegerField(choices=[(10, '10 Days'), (15, '15 Days'), (30, '30 Days'), (45, '45 Days'), (60, '60 Days')], default=10),
        ),
        migrations.AlterField(
            model_name='lpo',
            name='payment_option',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisitionexpenseitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisitionexpenseitem',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the expense'),
        ),
        migrations.AlterField(
            model_name='requisitionexpenseitem',
            name='expense_account',
            field=models.ForeignKey(limit_choices_to={'account_type': 'expense'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccounts'),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='delivered_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='manual_price_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='pricing_source',
            field=models.CharField(choices=[('system', 'System Price'), ('manual', 'Manual Price')], default='system', max_length=10),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitionitem_set', to='production.requisition'),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='system_price_at_creation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.taxcode'),
        ),
    ]
