# Generated by Django 5.0.6 on 2025-08-07 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_manufacturingrecord_paymentrecord_storebudget_and_more'),
        ('production', '0171_alter_requisitionexpenseitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Account used for payment (e.g., Cash, Bank, Accounts Payable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccounts'),
        ),
        migrations.AlterField(
            model_name='lpo',
            name='invoice_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/products/'),
        ),
    ]
