# Generated by Django 5.0.6 on 2025-08-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0172_add_payment_account_to_paymentvoucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesale',
            name='vat',
        ),
        migrations.AddField(
            model_name='storesale',
            name='billing_address',
            field=models.TextField(blank=True, help_text='Customer billing address', null=True),
        ),
        migrations.AddField(
            model_name='storesale',
            name='description',
            field=models.TextField(blank=True, help_text='Sale description or notes', null=True),
        ),
        migrations.AddField(
            model_name='storesale',
            name='tax_code',
            field=models.ForeignKey(blank=True, help_text='Tax code for this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.taxcode'),
        ),
    ]
