# Generated by Django 5.0.6 on 2025-08-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0173_remove_storesale_vat_storesale_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before tax', max_digits=10),
        ),
        migrations.AddField(
            model_name='storesale',
            name='withholding_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Withholding tax amount', max_digits=10),
        ),
    ]
