# Generated by Django 5.0.6 on 2025-08-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0174_storesale_subtotal_storesale_withholding_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10),
        ),
    ]
