# Generated by Django 5.0.6 on 2025-08-13 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0175_storesale_tax_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesalereceipt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Store Sale Receipt', 'verbose_name_plural': 'Store Sale Receipts'},
        ),
        migrations.RemoveField(
            model_name='storesalereceipt',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer email for payment notifications', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name for payment reference', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer contact for payment follow-up', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='delivered_by',
            field=models.ForeignKey(blank=True, help_text='User who marked as delivered', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='delivery_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when order was delivered', null=True),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for payment processing'),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='Date when payment is due', null=True),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue')], default='pending', help_text='Current payment status', max_length=20),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='payment_terms',
            field=models.CharField(default='45 days from delivery', help_text='Payment terms', max_length=100),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='reference_number',
            field=models.CharField(blank=True, help_text='External reference number', max_length=50),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before tax', max_digits=10),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='tax_code',
            field=models.CharField(blank=True, help_text='Tax code applied to this receipt', max_length=50),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax rate percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storesalereceipt',
            name='receipt_number',
            field=models.CharField(help_text='Unique receipt number for payment reference', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='storesalereceipt',
            name='total_due',
            field=models.DecimalField(decimal_places=2, help_text='Total amount due for payment', max_digits=10),
        ),
        migrations.AlterField(
            model_name='storesalereceipt',
            name='total_vat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total VAT amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='storesalereceipt',
            name='withholding_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Withholding tax amount', max_digits=10),
        ),
    ]
