# Generated by Django 5.0.6 on 2025-08-13 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_manufacturingrecord_paymentrecord_storebudget_and_more'),
        ('production', '0176_alter_storesalereceipt_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesalereceipt',
            name='delivery_date',
            field=models.DateTimeField(blank=True, help_text='Date when order was delivered', null=True),
        ),
        migrations.CreateModel(
            name='StoreSalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(help_text='Unique payment reference number', max_length=50, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of payment')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid by customer', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('credit_card', 'Credit Card'), ('other', 'Other')], help_text='Method of payment', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('customer_name', models.CharField(help_text='Customer name for reference', max_length=200)),
                ('receipt_number', models.CharField(help_text='Receipt number being paid', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID (bank transfer, mobile money, etc.)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional payment notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(help_text='Bank account to debit (e.g., Bank Account)', on_delete=django.db.models.deletion.PROTECT, related_name='store_sale_bank_payments', to='accounts.chartofaccounts')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='production.storesalereceipt')),
                ('received_by', models.ForeignKey(blank=True, help_text='User who received the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('revenue_account', models.ForeignKey(help_text='Revenue account to credit (e.g., Sales Revenue)', on_delete=django.db.models.deletion.PROTECT, related_name='store_sale_payments', to='accounts.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Store Sale Payment',
                'verbose_name_plural': 'Store Sale Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
