# Generated by Django 5.0.6 on 2025-08-13 19:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0014_remove_staff_branch'),
        ('production', '0177_alter_storesalereceipt_delivery_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesale',
            options={'ordering': ['-order_date'], 'verbose_name': 'Store Sale Order', 'verbose_name_plural': 'Store Sale Orders'},
        ),
        migrations.AlterModelOptions(
            name='storesalereceipt',
            options={'ordering': ['-receipt_date'], 'verbose_name': 'Sales Receipt', 'verbose_name_plural': 'Sales Receipts'},
        ),
        migrations.RenameField(
            model_name='storesale',
            old_name='sale_date',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='storesale',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='storesale',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='storesalereceipt',
            name='delivered_by',
        ),
        migrations.RemoveField(
            model_name='storesalereceipt',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='storesalereceipt',
            name='payment_due_date',
        ),
        migrations.RemoveField(
            model_name='storesalereceipt',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='storesalereceipt',
            name='store_sale',
        ),
        migrations.RemoveField(
            model_name='storesalereceipt',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='storesalereceipt',
            name='tax_code',
        ),
        migrations.RemoveField(
            model_name='storesalereceipt',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='storesalereceipt',
            name='total_vat',
        ),
        migrations.RemoveField(
            model_name='storesalereceipt',
            name='withholding_tax',
        ),
        migrations.AddField(
            model_name='storesale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storesale',
            name='order_number',
            field=models.CharField(blank=True, help_text='Unique order number', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='storesale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('credit_card', 'Credit Card'), ('other', 'Other')], help_text='Method of payment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='receipt_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when receipt was created'),
        ),
        migrations.AlterField(
            model_name='storesale',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storesale',
            name='description',
            field=models.TextField(blank=True, help_text='Order description or notes', null=True),
        ),
        migrations.AlterField(
            model_name='storesale',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='storesale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before tax', max_digits=10, max_length=10),
        ),
        migrations.AlterField(
            model_name='storesale',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.taxcode'),
        ),
        migrations.AlterField(
            model_name='storesale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total order amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='storesalereceipt',
            name='customer_name',
            field=models.CharField(help_text='Customer name for payment reference', max_length=200),
        ),
        migrations.AlterField(
            model_name='storesalereceipt',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue')], default='paid', help_text='Current payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='storesalereceipt',
            name='total_due',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid in this receipt', max_digits=10),
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=20, unique=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('overdue', 'Overdue'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before tax', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10)),
                ('withholding_tax', models.DecimalField(decimal_places=2, default=0, help_text='Withholding tax amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total invoice amount', max_digits=10)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid', max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Invoice notes')),
                ('terms_conditions', models.TextField(blank=True, help_text='Payment terms and conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSMagicApp.customer')),
                ('store_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoice', to='production.storesale')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.taxcode')),
            ],
            options={
                'verbose_name': 'Sales Invoice',
                'verbose_name_plural': 'Sales Invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='production.salesinvoice'),
        ),
    ]
