# Generated by Django 5.0.6 on 2025-08-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0178_alter_storesale_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesalereceipt',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name for payment reference', max_length=200, null=True),
        ),
    ]
