# Generated by Django 5.0.6 on 2025-08-13 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_manufacturingrecord_paymentrecord_storebudget_and_more'),
        ('production', '0179_alter_storesalereceipt_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesalereceipt',
            name='accounts_receivable_account',
            field=models.ForeignKey(blank=True, help_text='Accounts Receivable account to credit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_receivable', to='accounts.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='storesalereceipt',
            name='receiving_account',
            field=models.ForeignKey(blank=True, help_text='Account to receive payment (e.g., Cash, Bank)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_received', to='accounts.chartofaccounts'),
        ),
    ]
