# Generated by Django 5.0.6 on 2025-08-13 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_manufacturingrecord_paymentrecord_storebudget_and_more'),
        ('production', '0180_storesalereceipt_accounts_receivable_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(help_text='Unique credit note number', max_length=20, unique=True)),
                ('credit_note_date', models.DateTimeField(auto_now_add=True, help_text='Date when credit note was created')),
                ('credit_note_type', models.CharField(choices=[('return', 'Customer Return'), ('refund', 'Refund'), ('adjustment', 'Invoice Adjustment'), ('discount', 'Discount/Allowance'), ('error', 'Invoice Error')], help_text='Type of credit note', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('customer_name', models.CharField(help_text='Customer name', max_length=200)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer contact', max_length=20, null=True)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email', max_length=254, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before tax', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total credit amount', max_digits=10)),
                ('reason', models.TextField(help_text='Reason for credit note')),
                ('reference_number', models.CharField(blank=True, help_text='External reference number', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts_receivable_account', models.ForeignKey(help_text='Accounts Receivable account to debit', on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes_receivable', to='accounts.chartofaccounts')),
                ('created_by', models.ForeignKey(help_text='User who created the credit note', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sales_invoice', models.ForeignKey(help_text='Related sales invoice', on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='production.salesinvoice')),
                ('sales_return_account', models.ForeignKey(help_text='Sales Returns account to credit', on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes_sales_return', to='accounts.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Credit Note',
                'verbose_name_plural': 'Credit Notes',
                'ordering': ['-credit_note_date'],
            },
        ),
    ]
