# Generated by Django 5.0.6 on 2025-08-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0182_manufactureproduct_can_release_to_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('airtel_money', 'Airtel Money'), ('visa', 'Visa'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
