# Generated by Django 5.0.6 on 2025-08-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0183_update_payment_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesale',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the sale was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='servicesale',
            name='invoice_status',
            field=models.CharField(choices=[('not_invoiced', 'Not Invoiced'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='not_invoiced', max_length=20),
        ),
        migrations.AddField(
            model_name='servicesale',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, help_text='When the sale was invoiced', null=True),
        ),
        migrations.AddField(
            model_name='servicesale',
            name='payment_processing_time',
            field=models.DurationField(blank=True, help_text='Time taken to process payment', null=True),
        ),
        migrations.AddField(
            model_name='servicesale',
            name='sale_creation_time',
            field=models.DurationField(blank=True, help_text='Time taken to create the sale', null=True),
        ),
        migrations.AddField(
            model_name='servicesale',
            name='total_workflow_time',
            field=models.DurationField(blank=True, help_text='Total time from sale creation to payment completion', null=True),
        ),
    ]
