# Generated by Django 5.0.6 on 2025-08-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0184_add_invoice_status_and_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactureproduct',
            name='total_production_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total production cost for this batch', max_digits=15, null=True),
        ),
    ]
