# Generated by Django 5.0.6 on 2025-08-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0185_manufactureproduct_total_production_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesale',
            name='queue_start_time',
            field=models.DateTimeField(blank=True, help_text='When customer entered the queue', null=True),
        ),
        migrations.AddField(
            model_name='servicesale',
            name='queue_waiting_time',
            field=models.DurationField(blank=True, help_text='Time spent waiting in queue', null=True),
        ),
        migrations.AddField(
            model_name='servicesale',
            name='service_duration',
            field=models.DurationField(blank=True, help_text='Total time spent on service', null=True),
        ),
        migrations.AddField(
            model_name='servicesale',
            name='service_end_time',
            field=models.DateTimeField(blank=True, help_text='When service was completed', null=True),
        ),
        migrations.AddField(
            model_name='servicesale',
            name='service_start_time',
            field=models.DateTimeField(blank=True, help_text='When service actually started', null=True),
        ),
    ]
