# Generated by Django 5.0.6 on 2025-08-26 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0015_customer_can_make_purchases_and_more'),
        ('production', '0187_savedcommissionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesale',
            name='service_recipient',
            field=models.ForeignKey(blank=True, help_text='Who actually received the service (can be different from customer)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_received', to='POSMagicApp.customer'),
        ),
        migrations.AlterField(
            model_name='servicesale',
            name='customer',
            field=models.ForeignKey(help_text='Account holder/Payer', on_delete=django.db.models.deletion.CASCADE, related_name='service_sales', to='POSMagicApp.customer'),
        ),
    ]
