# Generated by Django 5.0.6 on 2025-09-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0189_servicecategory_servicename_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='accessorysaleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='internalaccessoryrequestitem',
            name='quantity_requested',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='mainstoreaccessoryrequisitionitem',
            name='quantity_requested',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='storeaccessoryinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
