# Generated by Django 5.0.6 on 2025-09-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0190_alter_accessoryinventory_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesale',
            name='slot_number',
            field=models.PositiveIntegerField(blank=True, help_text='Queue slot number for this customer', null=True),
        ),
    ]
