# Generated by Django 5.0.6 on 2025-09-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0018_loyaltysettings_customer_joined_loyalty_date_and_more'),
        ('production', '0191_servicesale_slot_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sale_number', models.CharField(editable=False, max_length=20, null=True, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_status', models.CharField(choices=[('not_paid', 'Not Paid'), ('paid', 'Paid')], default='not_paid', max_length=20)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('airtel_money', 'Airtel Money'), ('visa', 'Visa'), ('mixed', 'Mixed')], default='cash', max_length=255)),
                ('payment_remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('sale_creation_time', models.DurationField(blank=True, help_text='Time taken to create the sale', null=True)),
                ('payment_processing_time', models.DurationField(blank=True, help_text='Time taken to process payment', null=True)),
                ('total_workflow_time', models.DurationField(blank=True, help_text='Total time from sale creation to payment completion', null=True)),
                ('customer', models.ForeignKey(help_text='Customer who purchased the products', on_delete=django.db.models.deletion.CASCADE, related_name='product_sales', to='POSMagicApp.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sales', to='production.store')),
            ],
            options={
                'verbose_name': 'Product Sale',
                'verbose_name_plural': 'Product Sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='StoreProductSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.storeinventory')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sale_items', to='production.storeproductsale')),
            ],
            options={
                'verbose_name': 'Product Sale Item',
                'verbose_name_plural': 'Product Sale Items',
            },
        ),
    ]
