# Generated by Django 5.0.6 on 2025-09-29 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0192_storeproductsale_storeproductsaleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('airtel_money', 'Airtel Money'), ('visa', 'Visa'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='production.storeproductsale')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSaleReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, help_text='Unique receipt number', max_length=20, unique=True)),
                ('customer_name', models.CharField(help_text='Customer name for receipt', max_length=200)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone number', max_length=20, null=True)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email address', max_length=254, null=True)),
                ('receipt_date', models.DateTimeField(auto_now_add=True, help_text='Date and time receipt was generated')),
                ('total_due', models.DecimalField(decimal_places=2, help_text='Total amount due for the sale', max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid so far', max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, help_text='Remaining balance to be paid', max_digits=10)),
                ('is_paid', models.BooleanField(default=False, help_text='Whether the receipt is fully paid')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Whether the receipt is cancelled')),
                ('staff_name', models.CharField(help_text='Staff member who handled the sale', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the receipt')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='production.storeproductsale')),
                ('store', models.ForeignKey(help_text='Store where the sale was made', on_delete=django.db.models.deletion.CASCADE, to='production.store')),
            ],
            options={
                'verbose_name': 'Product Sale Receipt',
                'verbose_name_plural': 'Product Sale Receipts',
                'ordering': ['-receipt_date'],
            },
        ),
    ]
