# Generated by Django 5.0.6 on 2025-11-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0193_productsalepayment_productsalereceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refreshment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost price per unit', max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
