# Generated by Django 5.0.6 on 2025-11-19 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0194_refreshment'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshment',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refreshments', to='production.store'),
        ),
        migrations.AlterUniqueTogether(
            name='refreshment',
            unique_together={('store', 'name')},
        ),
    ]
