# Generated by Django 5.0.6 on 2025-11-19 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0195_refreshment_store_alter_refreshment_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshmentStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('addition', 'Stock Addition'), ('deduction', 'Stock Deduction'), ('update', 'Stock Update'), ('sale', 'Sale'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for addition, negative for deduction')),
                ('previous_quantity', models.IntegerField(help_text='Quantity before this action')),
                ('new_quantity', models.IntegerField(help_text='Quantity after this action')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, help_text='Reference ID (e.g., order number, adjustment ID)', max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('refreshment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='production.refreshment')),
            ],
            options={
                'verbose_name_plural': 'Refreshment Stock History',
                'ordering': ['-created_at'],
            },
        ),
    ]
