# Generated by Django 5.0.6 on 2025-11-19 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0196_refreshmentstockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshmentSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refreshment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.refreshment')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refreshment_sale_items', to='production.servicesale')),
            ],
        ),
    ]
