# Generated by Django 5.0.6 on 2025-11-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0199_servicesale_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdrawertransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile_money', 'MTN Momo'), ('airtel_money', 'Airtel Money'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20),
        ),
    ]
