# Generated by Django 5.0.6 on 2025-11-24 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0200_alter_cashdrawertransaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductsale',
            name='cash_drawer_session',
            field=models.ForeignKey(blank=True, help_text='The cash drawer session this sale is associated with', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_sales', to='production.cashdrawersession'),
        ),
    ]
