# Generated by Django 5.0.6 on 2025-11-27 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0203_alter_productsalepayment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnoteitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.storeaccessoryinventory'),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('service', 'Service'), ('product', 'Product'), ('accessory', 'Accessory'), ('refreshment', 'Refreshment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='refreshment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.refreshment'),
        ),
        migrations.AddField(
            model_name='servicesale',
            name='credit_notes',
            field=models.ManyToManyField(blank=True, related_name='service_sales', to='production.storecreditnote'),
        ),
        migrations.AddField(
            model_name='storeproductsale',
            name='credit_notes',
            field=models.ManyToManyField(blank=True, related_name='product_sales', to='production.storecreditnote'),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.storeinventory'),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.storeservice'),
        ),
        migrations.AlterField(
            model_name='storecreditnote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('exchanged', 'Exchanged'), ('refunded', 'Refunded'), ('void', 'Void')], default='draft', max_length=20),
        ),
    ]
