# Generated by Django 5.0.6 on 2025-12-01 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0204_remove_creditnoteitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdrawertransaction',
            name='store_credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_drawer_transactions', to='production.storecreditnote'),
        ),
        migrations.AlterField(
            model_name='cashdrawertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('expense', 'Expense'), ('float', 'Float Addition'), ('withdrawal', 'Withdrawal'), ('credit_note_refund', 'Credit Note Refund'), ('credit_note_void', 'Credit Note Void'), ('other', 'Other')], max_length=20),
        ),
    ]
