# Generated by Django 5.0.6 on 2026-01-26 11:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0205_cashdrawertransaction_store_credit_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdrawersession',
            name='carry_forward_float',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Amount of cash kept in drawer to start next session (float). Defaults to this session's opening balance if not set.", max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lpo',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='lpo',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
