# Generated by Django 5.0.6 on 2026-01-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0206_cashdrawersession_carry_forward_float_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livaramainstore',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='livaramainstore',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='manufacturedproductinventory',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='manufacturedproductinventory',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
