# Generated by Django 5.2.10 on 2026-02-04 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_chartofaccounts_account_category_and_more'),
        ('production', '0207_livaramainstore_total_cost_livaramainstore_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text="Default bank account for this store's deposits", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores_bank_accounts', to='accounts.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='store',
            name='cash_account',
            field=models.ForeignKey(blank=True, help_text="Cash-at-hand account for this store's till", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores_cash_accounts', to='accounts.chartofaccounts'),
        ),
    ]
