# Generated by Django 5.0.6 on 2026-02-04 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_chartofaccounts_account_category_and_more'),
        ('production', '0208_store_bank_account_store_cash_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='revenue_account',
            field=models.ForeignKey(blank=True, help_text='Revenue account for this category (child of 4120 Store Service Revenue), e.g. 4101 Treatment, 4111 Barber Shop.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_categories', to='accounts.chartofaccounts'),
        ),
    ]
