# Generated by Django 5.0.6 on 2026-02-04 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_chartofaccounts_account_category_and_more'),
        ('production', '0209_servicecategory_revenue_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='payables_account',
            field=models.ForeignKey(blank=True, help_text='AP account for this supplier (child of 2000 Accounts Payable - Suppliers)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='accounts.chartofaccounts'),
        ),
    ]
