from django.urls import path
from .views import  AccessoryRequisitonView, ApproveStoreTransferView, DeliverRestockRequestView, LpoDetailView, ProDeView, delete_rawmaterial, purhcaseOrderDetails
from . import views

urlpatterns = [
    path('production-dashboard/', views.productionPage, name='productionPage'),
    path('suppliers/', views.supplierList, name='supplierList'),
    path('add-supplier/', views.addSupplier, name='addSupplier'),
    path('edit-supplier/<int:supplier_id>/', views.editSupplier, name='editSupplier'),
    path('delete-supplier/<int:supplier_id>/', views.deleteSupplier, name='deleteSupplier'),
    path('supplier_details/<int:supplier_id>/', views.supplier_details, name='supplier_details'),
    path('error_page/', views.error_page, name="error"),
    
    path('raw-materials/', views.rawmaterialsList, name='rawmaterialsList'),
    path('add-raw-materials/', views.addRawmaterial, name='addRawmaterial'),
    path('download-example-csv/', views.download_example_csv, name='download_example_csv'),
    path('download-supplier-csv,', views.download_supplier_csv, name="download_supplier_csv"),
    path('delete_rawmaterial/<int:raw_material_id>/', delete_rawmaterial, name='delete_rawmaterial'),
    path('raw-material/<int:pk>/', views.update_raw_material_quantity, name="update_raw_material_quantity"),
    path('rawamaterialsTable/', views.rawamaterialsTable, name="rawamaterialsTable"),
    path('debit_notes_list/', views.debit_notes_list, name="debit_notes_list"),
    path('debit_note_details/<int:debit_note_id>/', views.debit_note_details, name="debit_note_details"),
    path('replace_notes_list/', views.replace_notes_list, name="replace_notes_list"),
    path('replace_note_details/<int:replace_note_id>/', views.replace_note_details, name="replace_note_details"),
    path('process_replacements/<int:replace_note_id>/', views.process_replacements, name="process_replacements"),

    
    path('create_requisition/', views.create_requisition, name='create_requisition'),
    path('get_raw_materials/', views.get_raw_materials_by_supplier, name='get_raw_materials'),
    path('all_requisitions/', views.all_requisitions, name='all_requisitions'),
    path('requisition_details/<int:requisition_id>/', views.requisition_details, name='requisition_details'),
    path('delete_requisition/<int:requisition_id>/', views.delete_requisition, name='delete_requisition'),
    path('approve-requisition/<int:requisition_id>/', views.approve_requisition, name='approve_requisition'),
    path('reject-requisition/<int:requisition_id>/', views.reject_requisition, name='reject_requisition'),
    path('get_raw_materials_by_supplier/', views.get_raw_materials_by_supplier, name='get_raw_materials_by_supplier'),
    
    path('lpos_list/', views.lpo_list, name='lpos_list'),
    path('lpo<int:pk>/', views.lpo_verify, name='lpo_verify'),
    path('lpo/<int:pk>/', LpoDetailView.as_view(), name='lpo_detail'),
    # path('process_delivery/<int:requisition_id>/', views.process_delivery, name='process_delivery'),
    path('process_delivery/<int:requisition_id>/', ProDeView.as_view(), name='process_del'),
    path('pay_lpo/<int:lpo_id>/', views.pay_lpo, name='pay_lpo'),
    
    
    
    path('production_payment_vouchers/', views.production_payment_vouchers, name="production_payment_vouchers"),
    path('production_payment_voucher_detail/<str:voucher_number>/', views.production_payment_voucher_detail, name="production_payment_voucher_details"),
    
    path('goods-received-notes/', views.goods_recieved_notes, name='goods_received_note_list'),
    path('goods_received_note_detail/<int:note_id>', views.goods_received_note_detail, name='goods_received_note_detail'),
    path('goods-received-notes/<int:note_id>/handle-discrepancy/', views.handle_discrepancy, name='handle_discrepancy'),
    
    path('discrepancy_delivery_report_detail/<int:report_id>/', views.discrepancy_delivery_report_detail, name='discrepancy_delivery_report_detail'),
    path('discrepancy_delivery_report_list/', views.discrepancy_delivery_report_list, name='discrepancy_delivery_report_list'),
    
    path('store-management/', views.storeManagement, name='storeManagement'),
    path('dispatch-list/', views.dispatchList, name='dispatchList'),
    path('store-products/', views.storeProducts, name='storeProducts'),
    path('production-process/', views.productionProcess, name='productionProcess'),
    path('store-requests/', views.storeRequests, name='storeRequests'),
    path('purchase-order-list/', views.purchaseOderList, name='purchaseOderList'),
    path('create-purchase-order/<int:rawmaterial_id>/', views.createPurchaseOrder, name='createPurchaseOrder'),
    path('purhcase_order/<int:purchase_order_id>', views.purhcaseOrderDetails, name='purchase_order_details'),
    path('edit-purchase-order/<int:purchase_order_id>/', views.editPurchaseOrderDetails, name='edit_purchase_order_details'),
    path('products-list/', views.productsList, name='productsList'),
    path('product-details/<int:product_id>/', views.productDetails, name='productDetailsPage'),
    path('create-product/', views.create_product, name='createProduct'),
    path('test-product/<int:product_id>', views.testProduct, name='testProduct'),
    path('edit-product/<int:product_id>/', views.edit_product, name='editProduct'),
    path('manufacture-product/<int:product_id>/', views.manufacture_product, name='manufactureProduct'),
    path('manufactured-product-list/', views.manufactured_products_list, name='manufacturedProductList'),
    path('factory-inventory/', views.factory_inventory, name='factoryInventory'),
    path('manufactured-product-details/<int:product_id>/', views.manufacturedproduct_detail, name="manufacturedProductDetails"),
    path('product-inventory-details/<int:inventory_id>/', views.product_inventory_details, name="productInventoryDetails"),
    path('write_off_inventory/<int:inventory_id>/', views.write_off_product, name="write_off_inventory"),
    path('all-stores/', views.all_stores, name="allStores"),
    path('add-store/', views.add_store, name="addStore"),
    path('edit-store/<int:store_id>', views.edit_store, name="editStore"),
    path('delete-store/<int:store_id>/', views.delete_store, name="deleteStore"),
    path('restock-requests/', views.restock_requests, name="restockRequests"),
    path('create-restock-request/', views.create_restock_request, name="createRestockRequest"),
    path('restock_request_detail/<int:restock_id>/', views.restock_request_detail, name="restock_request_detail"),
    path('mark_restock_as_delivered/<int:restock_id>', views.mark_restock_as_delivered, name="restock_delivered"),
    
    path('manager_inventory_view/', views.manager_inventory_view, name="manager_inventory_view"),
    path('inventory_adjustments/<int:inventory_id>', views.inventory_adjustments, name="inventory_adjustments"),
    path('main_store_inventory_adjustments/', views.main_store_inventory_adjustments, name="main_store_inventory_adjustments"),
    path('store_services_view/', views.store_services_view, name="store_services_view"),
    path('branch_staff_view/', views.branch_staff_view, name="branch_staff_view"),

    path('approve-restock-request/<int:request_id>', views.approve_restock_requests, name="approve_restock_requests"),
    path('general-stores/', views.store_inventory_list, name="store_inventory_list"),
    path('bulk_stock_tansfer/', views.bulk_stock_transfer, name="bulk_stock_transfer"),
    # path('approve_store_transfer/<int:pk>/',views.approve_store_transfer, name="approve_store_transfer"),
    path('approve_store_request/<int:pk>/', ApproveStoreTransferView.as_view(), name="approve_store_request"),
    path('deliver_store_request/<int:pk>/', DeliverRestockRequestView.as_view(), name="deliver_store_request"),
    
    path('complete_livara_ms_transfer/', views.mark_transfer_completed, name="mark_transfer_completed"),
    path('main_stock_transfers/', views.main_stock_transfer, name="main_stock_transfer"),
    path('livara_main_store_inventory', views.livara_main_store_inventory, name="livara_main_store_inventory"),
    ##acessroies mainstore##
    path('accessory_store/', views.accessory_store, name="accessory_store"),
    path('create_new_accessory/', views.create_new_accessory, name="create_new_accessory"),
    path('main_store_accessory_requisitions_list/', views.main_store_accessory_requisitions_list, name="main_store_accessory_requisitions_list"),
    path('create_accessory_requisition/', views.create_accessory_requisition, name="create_accessory_requisition"),
    path('accessory_requisition_details/<int:pk>/', AccessoryRequisitonView.as_view(), name="accessory_requisition_details"),
    path('process_acccessory_requisition/<int:requisition_id>/', views.process_acccessory_requisition, name="process_acccessory_requisition"),
    path('particular_store_inventory/', views.particular_store_inventory, name="particular_store_inventory"),
    path('create_internal_requests/', views.create_internal_requests, name="create_internal_requests"),
    path('store_internal_requests/', views.store_internal_requests, name="store_internal_requests"),
    path('all_internal_requests/', views.all_internal_requests, name="all_internal_requests"),
    path('internal_request_detail/<int:request_id>/', views.internal_request_detail, name="internal_request_detail"),
    path('process_internal_request/<int:request_id>/', views.process_internal_request, name="process_internal_request"),
    path('mark_request_as_delivered/<int:request_id>/', views.mark_as_delivered, name="mark_as_delivered"),
    path('all_stores_inventory_view/', views.all_stores_inventory_view, name="all_stores_inventory_view"),
    path('accessory_stock_adjustment_view/', views.accessory_stock_adjustment_view, name="accessory_stock_adjustment_view"),
    path('reports/manager_store_accessory_report/', views.manager_store_accessory_report, name="manager_store_accessory_report"),
    path('accessory_inventory_report/', views.accessory_inventory_report, name="accessory_inventory_report"),
    
    ####Sales###
    path('create_service_sale/', views.create_service_sale, name="create_service_sale"),
    path('update_service_sale/<int:pk>/', views.update_service_sale, name="update_service_sale"),
    path('store_sale_list/', views.store_sale_list, name="store_sale_list"),
    path('service_sale_details/<int:sale_id>/', views.service_sale_details, name="service_sale_details"),
    path('store_sale_service_invoice_list/', views.store_sale_service_invoice_list, name="store_sale_service_invoice_list"),
    path('raw_material_date_report/', views.raw_material_date_report, name="raw_material_date_report"),
    
    path('reject-request/<int:request_id>/', views.reject_restock_request, name="reject_request"),
    path('finance-approval/<int:request_id>', views.finance_approve_request, name="finance_approval"),
    path('create_production_order/', views.create_production_order, name="create_production_order"),
    path('production-orders/', views.list_production_orders, name='productionList'),
    path('finance-approval/<int:pk>/', views.approve_production_order, name='approveProduction'),
    path('finance-production-orders/', views.finance_view_production_orders, name='financeProduction'),
    path('production-production-orders/', views.productions_view_production_orders, name='productionProduction'),
    path('start-progress/<int:pk>/', views.start_production_progress, name='startProgress'),
    path('finance-purchase-orders/', views.finance_view_purchase_orders, name='financePurchase'),
    path('orders/approve/<int:order_id>/', views.approve_order, name='approve_order'),
    path('orders/reject/<int:order_id>/', views.reject_order, name='reject_order'),
    
    path('approve-purchase-orders/<int:purchaseo_id>', views.approve_purchase_order, name='approvePurchaseOrder'),
    path('finance-restock-requests/', views.finance_restock_requests, name='financeRestockRequests'),
    
    path('create_store_sale/', views.create_store_sale, name='createStoreSale'),
    path('list_store_sales/', views.list_store_sales, name='listStoreSales'),
    path('test_sale/', views.create_store_test, name="SaleTest"),
    path('get_wholesale_price/',views.get_wholesale_price, name="get_wholesale_price"),
    path('update_order_status/<int:store_sale_id>/', views.update_order_status, name='update_order_status'),
    path('finance_list_store_sales/', views.finance_list_store_sales, name="financeListStoreSales"),
    path('pay_order_status/<int:store_sale_id>/', views.pay_order_status, name='pay_order_status'),
    path('store_sale_order_details/<int:pk>/', views.store_sale_order_details, name='store_sale_order_details'),
    path('mark_transfer_completed/<int:transfer_id>/', views.mark_transfer_completed, name='mark_transfer_completed'),
    
    path('write_offs', views.write_offs, name="writeoffs"),
    path('manufacture_products_report', views.manufactured_products_report, name="manufactured_products_report"),
    path('raw_material_utilization_report/', views.raw_material_utilization_report, name='raw_material_utilization_report'),
    path('raw_material_utilization_reports/', views.raw_material_utilization_reports, name="raw_material_utilization_reports"),
    
    ## Store Manager View
    path('store_manager/', views.managers_store_inventory_view, name='managers_store_inventory_view'),
    
    ##finance
    path('outstanding_payables/',  views.outstanding_payables, name='outstanding_payables'),
    path('create_incident_write_off/', views.create_incident_write_off, name="create_incident_write_off"),
    path('incident_write_off_list/', views.incident_write_off_list, name='incident_write_off_list'),
    
    path('update_reorder_point/<int:pk>/', views.update_reorder_point, name="update_reorder_point"),
]