from django.urls import path
from .views import purhcaseOrderDetails
from . import views

urlpatterns = [
    path('production-dashboard/', views.productionPage, name='productionPage'),
    path('suppliers/', views.supplierList, name='supplierList'),
    path('add-supplier/', views.addSupplier, name='addSupplier'),
    path('edit-supplier/<int:supplier_id>/', views.editSupplier, name='editSupplier'),
    path('delete-supplier/<int:supplier_id>/', views.deleteSupplier, name='deleteSupplier'),
    path('raw-materials/', views.rawmaterialsList, name='rawmaterialsList'),
    path('add-raw-materials/', views.addRawmaterial, name='addRawmaterial'),
    path('store-management/', views.storeManagement, name='storeManagement'),
    path('dispatch-list/', views.dispatchList, name='dispatchList'),
    path('store-products/', views.storeProducts, name='storeProducts'),
    path('production-process/', views.productionProcess, name='productionProcess'),
    path('store-requests/', views.storeRequests, name='storeRequests'),
    path('purchase-order-list/', views.purchaseOderList, name='purchaseOderList'),
    path('create-purchase-order/<int:rawmaterial_id>/', views.createPurchaseOrder, name='createPurchaseOrder'),
    path('purhcase_order/<int:purchase_order_id>', views.purhcaseOrderDetails, name='purchase_order_details'),
    path('edit-purchase-order/<int:purchase_order_id>/', views.editPurchaseOrderDetails, name='edit_purchase_order_details'),
    path('products-list/', views.productsList, name='productsList'),
    path('product-details/<int:product_id>/', views.productDetails, name='productDetailsPage'),
    path('create-product/', views.create_product, name='createProduct'),
    path('test-product/<int:product_id>', views.testProduct, name='testProduct'),
    path('edit-product/<int:product_id>/', views.edit_product, name='editProduct'),
    path('manufacture-product/<int:product_id>/', views.manufacture_product, name='manufactureProduct'),
    path('manufactured-product-list/', views.manufactured_products_list, name='manufacturedProductList'),
    path('factory-inventory/', views.factory_inventory, name='factoryInventory'),
    path('manufactured-product-details/<int:product_id>/', views.manufacturedproduct_detail, name="manufacturedProductDetails"),
    path('product-inventory-details/<int:inventory_id>/', views.product_inventory_details, name="productInventoryDetails"),
    path('all-stores/', views.all_stores, name="allStores"),
    path('add-store/', views.add_store, name="addStore"),
    path('edit-store/<int:store_id>', views.edit_store, name="editStore"),
    path('delete-store/<int:store_id>/', views.delete_store, name="deleteStore"),
    path('restock-requests/', views.restock_requests, name="restockRequests"),
    path('create-restock-request/', views.create_restock_request, name="createRestockRequest"),
    path('edit-restock-request/<int:request_id>/', views.edit_restock_request, name="editRestockRequests"),
    path('approve-restock-request/<int:request_id>', views.approve_restock_requests, name="approve_restock_requests"),
    path('general-stores/', views.store_inventory_list, name="store_inventory_list"),
    path('reject-request/<int:request_id>/', views.reject_restock_request, name="reject_request"),
    path('finance-approval/<int:request_id>', views.finance_approve_request, name="finance_approval"),
    path('create_production_order/', views.create_production_order, name="create_production_order"),
    path('production-orders/', views.list_production_orders, name='productionList'),
    path('finance-approval/<int:pk>/', views.approve_production_order, name='approveProduction'),
    path('finance-production-orders/', views.finance_view_production_orders, name='financeProduction'),
    path('production-production-orders/', views.productions_view_production_orders, name='productionProduction'),
    path('start-progress/<int:pk>/', views.start_production_progress, name='startProgress'),
    path('finance-purchase-orders/', views.finance_view_purchase_orders, name='financePurchase'),
    path('approve-purchase-orders/<int:purchaseo_id>', views.approve_purchase_order, name='approvePurchaseOrder'),
    path('finance-restock-requests/', views.finance_restock_requests, name='financeRestockRequests'),
    path('finance_approve_restock_request/<int:pk>', views.finance_approve_restock_requests, name='approveRestockRequest'),
    path('create_store_sale/', views.create_store_sale, name='createStoreSale'),
    path('list_store_sales/', views.list_store_sales, name='listStoreSales'),
    path('test_sale/', views.create_store_test, name="SaleTest"),
    path('update_order_status/<int:store_sale_id>/', views.update_order_status, name='update_order_status'),
    path('finance_list_store_sales/', views.finance_list_store_sales, name="financeListStoreSales"),
    path('pay_order_status/<int:store_sale_id>/', views.pay_order_status, name='pay_order_status'),
    
]