# Generated by Django 5.0.6 on 2025-07-26 08:07

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0165_alter_requisitionitem_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('current_assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fixed_assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('current_liabilities', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('long_term_liabilities', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('owner_equity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('retained_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_equity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-as_of_date'],
                'unique_together': {('as_of_date',)},
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(help_text='Account number (e.g., 1000, 2000)', max_length=10, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('account_category', models.CharField(choices=[('current_asset', 'Current Asset'), ('fixed_asset', 'Fixed Asset'), ('intangible_asset', 'Intangible Asset'), ('current_liability', 'Current Liability'), ('long_term_liability', 'Long Term Liability'), ('owner_equity', 'Owner Equity'), ('retained_earnings', 'Retained Earnings'), ('operating_revenue', 'Operating Revenue'), ('other_revenue', 'Other Revenue'), ('cost_of_goods_sold', 'Cost of Goods Sold'), ('operating_expense', 'Operating Expense'), ('administrative_expense', 'Administrative Expense'), ('financial_expense', 'Financial Expense')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='accounts.chartofaccounts')),
            ],
            options={
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['account_code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('reference', models.CharField(blank=True, help_text='Reference number or description', max_length=255)),
                ('description', models.TextField()),
                ('entry_type', models.CharField(choices=[('manual', 'Manual Entry'), ('system', 'System Generated'), ('production', 'Production Related'), ('sales', 'Sales Related'), ('purchase', 'Purchase Related')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='accounts.department')),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounts.chartofaccounts')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.journalentry')),
            ],
            options={
                'ordering': ['entry_type', 'account__account_code'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.chartofaccounts')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.department')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('department', 'account', 'period', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='ProductionExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_expenses', to='accounts.journalentry')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entries', to='production.requisition')),
            ],
            options={
                'unique_together': {('requisition', 'journal_entry')},
            },
        ),
        migrations.CreateModel(
            name='ProfitLossStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('operating_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('other_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_loss_statements', to='accounts.financialperiod')),
            ],
            options={
                'ordering': ['-period__start_date'],
                'unique_together': {('period',)},
            },
        ),
        migrations.CreateModel(
            name='SalesRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_revenues', to='accounts.journalentry')),
                ('service_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entries', to='production.servicesale')),
                ('store_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entries', to='production.storesale')),
            ],
            options={
                'unique_together': {('journal_entry',)},
            },
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccounts')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balances', to='accounts.financialperiod')),
            ],
            options={
                'ordering': ['account__account_code'],
                'unique_together': {('period', 'account')},
            },
        ),
    ]
