# Generated by Django 5.0.6 on 2025-08-25 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_manufacturingrecord_paymentrecord_storebudget_and_more'),
        ('production', '0184_add_invoice_status_and_timing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_records', to='production.payment'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='service_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='production.servicesale'),
        ),
        migrations.AlterField(
            model_name='salesrevenue',
            name='service_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to='production.servicesale'),
        ),
        migrations.AlterField(
            model_name='salesrevenue',
            name='store_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to='production.storesale'),
        ),
        migrations.CreateModel(
            name='CommissionExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission_type', models.CharField(choices=[('service', 'Service Commission'), ('product', 'Product Commission'), ('monthly', 'Monthly Commission Payment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_expenses', to='accounts.journalentry')),
                ('monthly_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_records', to='production.monthlystaffcommission')),
                ('product_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_records', to='production.staffproductcommission')),
                ('staff_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_records', to='production.staffcommission')),
            ],
        ),
    ]
