# Generated by Django 5.0.6 on 2026-01-26 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_paymentrecord_unique_together_and_more'),
        ('production', '0206_cashdrawersession_carry_forward_float_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_category',
            field=models.CharField(choices=[('current_asset', 'Current Asset'), ('fixed_asset', 'Fixed Asset'), ('intangible_asset', 'Intangible Asset'), ('current_liability', 'Current Liability'), ('long_term_liability', 'Long Term Liability'), ('owner_equity', 'Owner Equity'), ('retained_earnings', 'Retained Earnings'), ('operating_revenue', 'Operating Revenue'), ('other_revenue', 'Other Revenue'), ('contra_revenue', 'Contra Revenue'), ('cost_of_goods_sold', 'Cost of Goods Sold'), ('operating_expense', 'Operating Expense'), ('administrative_expense', 'Administrative Expense'), ('financial_expense', 'Financial Expense'), ('tax_expense', 'Tax Expense'), ('tax_receivable', 'Tax Receivable'), ('tax_payable', 'Tax Payable')], max_length=30),
        ),
        migrations.CreateModel(
            name='CashDrawerBanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_date', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(help_text='Bank account (e.g., Equity Bank, Stanbic Bank)', on_delete=django.db.models.deletion.PROTECT, related_name='cash_deposits', to='accounts.chartofaccounts')),
                ('cash_drawer_account', models.ForeignKey(help_text='Cash-on-hand / till account', on_delete=django.db.models.deletion.PROTECT, related_name='cash_drawer_deposits', to='accounts.chartofaccounts')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_drawer_banking', to='accounts.journalentry')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_deposits', to='production.cashdrawersession')),
            ],
            options={
                'ordering': ['-deposit_date'],
            },
        ),
    ]
