# Generated by Django 5.0.6 on 2026-02-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0018_loyaltysettings_customer_joined_loyalty_date_and_more'),
        ('accounts', '0004_alter_chartofaccounts_account_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionexpense',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_expenses', to='POSMagicApp.staff'),
        ),
    ]
