# Generated by Django 3.2.5 on 2024-04-10 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POSMagicApp.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.CharField(choices=[('HAIR_CARE', 'Hair Care'), ('STYLING', 'Styling'), ('OTHER', 'Other'), ('BARBER', 'Barber'), ('NAIL_ARTIST', 'Nail Artist'), ('MASSEUSE', 'Masseuse')], default='OTHER', max_length=100),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='staff',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='POSMagicApp.branch'),
        ),
    ]
