# Generated by Django 3.2.5 on 2024-04-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0003_auto_20240410_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BABERSHOP', 'Babershop'), ('HAIRCARE', 'Haircare'), ('KIDS_HAIR', 'Kids Hair'), ('DREADLOCKS', 'Dreadlocks'), ('NAIL_ART', 'Nail Art'), ('PRODUCTS', 'Products')], default='PRODUCTS', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
