# Generated by Django 3.2.5 on 2024-04-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0004_auto_20240410_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
