# Generated by Django 3.2.5 on 2024-04-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0005_remove_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type_of_customer',
            field=models.CharField(choices=[('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail')], default='RETAIL', max_length=100),
        ),
    ]
