# Generated by Django 3.2.5 on 2024-04-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0006_customer_type_of_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
