# Generated by Django 3.2.5 on 2024-04-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0007_customer_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='nin_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
