# Generated by Django 3.2.5 on 2024-04-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0008_auto_20240418_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default='/static//img/user/profile.jpg', null=True, upload_to='uploads/products/'),
        ),
    ]
