# Generated by Django 3.2.5 on 2024-05-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0009_customer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BABERSHOP', 'Babershop'), ('HAIRCARE', 'Haircare'), ('KIDS_HAIR', 'Kids Hair'), ('DREADLOCKS', 'Dreadlocks'), ('NAIL_ART', 'Nail Art'), ('PRODUCTS', 'Products'), ('SALOOMATERIALS', 'Service Materials')], default='PRODUCTS', max_length=20),
        ),
    ]
