# Generated by Django 5.0.6 on 2024-10-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0011_staff_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='branch',
        ),
    ]
