# Generated by Django 5.0.6 on 2025-03-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0013_staff_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='branch',
        ),
    ]
