# Generated by Django 5.0.6 on 2025-08-26 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0014_remove_staff_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='can_make_purchases',
            field=models.BooleanField(default=True, help_text='Can this person authorize purchases'),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='guardian',
            field=models.ForeignKey(blank=True, help_text='Parent/Guardian for minors', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='POSMagicApp.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_minor',
            field=models.BooleanField(default=False, help_text='Is this person under 18?'),
        ),
        migrations.AddField(
            model_name='customer',
            name='kyc_verified',
            field=models.BooleanField(default=False, help_text='Has completed KYC verification'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='relationship_to_guardian',
            field=models.CharField(choices=[('SELF', 'Self'), ('PARENT', 'Parent/Guardian'), ('CHILD', 'Child/Dependent'), ('SPOUSE', 'Spouse'), ('SIBLING', 'Sibling'), ('OTHER', 'Other Relative')], default='SELF', help_text='Relationship to account holder', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender - required for clients', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type_of_customer',
            field=models.CharField(choices=[('WHOLESALE', 'Wholesaler'), ('RETAIL', 'Retailer'), ('CLIENT', 'Client')], default='CLIENT', max_length=100),
        ),
    ]
