# Generated by Django 5.0.6 on 2025-08-27 00:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0015_customer_can_make_purchases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='', help_text='Customer profile picture', max_length=255, null=True, verbose_name='image'),
        ),
    ]
