# Generated by Django 5.0.6 on 2025-08-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSMagicApp', '0016_alter_customer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Customer profile picture', null=True, upload_to='customer_profiles/'),
        ),
    ]
